AWSTemplateFormatVersion: 2010-09-09
Description: CICD IAC Pipeline Stack
Parameters:
  AccountType:
    Description: The type of the account.
    Type: AWS::SSM::Parameter::Value<String>
    Default: /oeintegrations/accounttype
  BranchName:
    Description: The Git branch to watch
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /oeintegrations/cd/git/branch
Resources:
  CodeBuildProject:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: oe-integrations
      Description: CICD IAC Pipeline Stack
      Source:
        BuildSpec: buildspec.yml
        InsecureSsl: false
        Type: CODEPIPELINE
      Artifacts:
        EncryptionDisabled: false
        Name: oe-integrations
        Packaging: NONE
        Type: CODEPIPELINE
      Cache:
        Type: NO_CACHE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: 'aws/codebuild/amazonlinux2-x86_64-standard:3.0'
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: true
        Type: LINUX_CONTAINER
      ServiceRole: !Sub arn:aws:iam::${AWS::AccountId}:role/service-role/codebuild-oe-integration-build-project-service-role
      TimeoutInMinutes: 60
      QueuedTimeoutInMinutes: 480
      EncryptionKey: !Sub 'arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/s3'
      BadgeEnabled: false
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
          GroupName: oeintegrations
          StreamName: oe-integrations
        S3Logs:
          Status: DISABLED
          EncryptionDisabled: false
  ArtifactStore:
    Type: 'AWS::S3::Bucket'
    Properties: {}
  DeploymentPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Type: S3
        Location:
          Ref: ArtifactStore
      Name: oeintegrations
      RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/service-role/AWSCodePipelineServiceRole-us-east-2-open-exchange-Dev-Infrastr
      Stages:
        - Name: Source
          Actions:
            - Name: ApplicationSource
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              OutputArtifacts:
                - Name: oeintegrationsOutput
              Configuration:
                Branch: !Sub ${BranchName}
                OAuthToken: "{{resolve:secretsmanager:oeintegration/github/access:SecretString:ttoken}}"
                Owner: Knowledgevision
                PollForSourceChanges: false
                Repo: OE-Integration-Infrastructure
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: CodeBuild
              InputArtifacts:
                - Name: oeintegrationsOutput
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              OutputArtifacts:
                - Name: IACAppArtifact-oe-integrations
              Configuration:
                ProjectName: !Ref CodeBuildProject
              RunOrder: 1
        - Name: ApplyVpcTemplate
          Actions:
            - Name: vpc
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              InputArtifacts:
                - Name: oeintegrationsOutput
              OutputArtifacts: []
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/service-role/AWSCodePipelineServiceRole-us-east-2-open-exchange-Dev-Infrastr
                StackName: oe-integrations-vpc
                TemplatePath: oeintegrationsOutput::001-vpc.yml
              RunOrder: 1
        - Name: ApplyGatewayTemplates
          Actions:
            - Name: gateway
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              InputArtifacts:
                - Name: oeintegrationsOutput
              OutputArtifacts: []
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/service-role/AWSCodePipelineServiceRole-us-east-2-open-exchange-Dev-Infrastr
                StackName: oe-integrations-gateway
                TemplatePath: oeintegrationsOutput::002-gateway.yml
              RunOrder: 1
        - Name: ApplySubnetsTemplate
          Actions:
            - Name: subnets
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              InputArtifacts:
                - Name: oeintegrationsOutput
              OutputArtifacts: []
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/service-role/AWSCodePipelineServiceRole-us-east-2-open-exchange-Dev-Infrastr
                StackName: oe-integrations-subnets
                TemplatePath: oeintegrationsOutput::003-subnets.yml
              RunOrder: 1
        - Name: ApplyNatgatewayTemplate
          Actions:
            - Name: natgateway
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              InputArtifacts:
                - Name: oeintegrationsOutput
              OutputArtifacts: []
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/service-role/AWSCodePipelineServiceRole-us-east-2-open-exchange-Dev-Infrastr
                StackName: oe-integrations-natgateway
                TemplatePath: oeintegrationsOutput::0011-natgateway.yml
              RunOrder: 1
        - Name: ApplyRoutetablesTemplate
          Actions:
            - Name: routetables
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              InputArtifacts:
                - Name: oeintegrationsOutput
              OutputArtifacts: []
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/service-role/AWSCodePipelineServiceRole-us-east-2-open-exchange-Dev-Infrastr
                StackName: oe-integrations-routetables
                TemplatePath: oeintegrationsOutput::004-routetables.yml
              RunOrder: 1
        - Name: ApplyNetworkaclsTemplate
          Actions:
            - Name: networkacls
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              InputArtifacts:
                - Name: oeintegrationsOutput
              OutputArtifacts: []
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/service-role/AWSCodePipelineServiceRole-us-east-2-open-exchange-Dev-Infrastr
                StackName: oe-integrations-networkacls
                TemplatePath: oeintegrationsOutput::005-networkacls.yml
              RunOrder: 1
